# Generated by Django 4.2.6 on 2023-10-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='decription',
            field=models.CharField(max_length=255),
        ),
    ]
