# Generated by Django 4.2.6 on 2023-10-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basket_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='decription',
            field=models.CharField(max_length=500),
        ),
    ]
