# Generated by Django 4.2.6 on 2023-10-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basket_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
