# Generated by Django 4.2.6 on 2023-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_rename_decription_basket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image_url',
            field=models.URLField(default='https://www.aldi-nord.de/sortiment/backwaren-aufstriche-cerealien/brotaufstrich/bio-konfituere-extra-2977-0-0.article.html'),
        ),
    ]
